# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oiHhHABZSohWboyr1DKk4D0Io2SSRoFQd54y/dFWaHtodpKfxBpJYzsqc16P4Ps1gJ/JcJ5oSESfzFVDGqdKa6ROgFqwlaPfezqbMqNJd92OXp/obcBcgPTt77Ib60WcAzPxg/tuCn6A0hWElIdg2PYz0tFihP2mEt0QNsLxZc9VeeAbhbgBtQjr/+ER/Az4GnrIPvZttqZ7GUhdi4/kncf9FFHEocqm9nBKCDaLc74dcPjty1JphrtlCirr6xdLs3EdA8nanRM9taXfjgYhUaw5bL3oGBoPDWsoxQjBNzZ0euG3yNcK+PnCVXn0a0uJysGbeJOoLMjsRwNB1jCephl/I/XApyUxcaZ+yD8EAqnLqTEqQ49lgBcbgpWgTnDuIdij74ayfikd0WKdMDAiuqe/tH+LbJUw3x2Fnlqz4y01U2xvbHAKVKtx409dPj0vuupl6B8MWrZslqkbVt+z9tqCucfFVsg/x9xE/ObASDTq5/WzyfHqAz3Dhc2VPzGeIm0FBjinqNtc6F7vwh3EE+m8Kt02ZeXeB+zCqhYefStIl+m/E3dFohqIMCFgXh/2TjNOdA167Ncm2keJXvYtPl09Sv/1j/rxQ5cD44jiRUlap5MerUY1aRDtdyfRImktbUobtvWkqgiWvy6X46wGVo7oyVbgSpKqCThyQ69di/c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
