# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Hqqqm7fd6a0n/O161KJNS/KyD0Q2p3pbP6mqUCWjmw5wQiKJ5Rpa8jk5YbHh5Z44zsXwIbzCt5siqO4y6WNTC5f14dDo20AmiKdxgQ4UELV3SE017UPocg/2QWBY/i3gGCDiADty8ovYndnJr3IzRC28kUFthXRc1hTWddjCFkW5XGn/edZ0Ifa+MFuen45LMIW8RMOH+kJtKan+oyvfkJfYPhZyUo5pm00Gf2aw5899aWHLsTA05yAAa4WQRqinfld3ID9N3+XyHdVjkjfJdoYN/Yg/2++QS4o7x9J/vMM+24G7ePxJnU8TWPLj21tf1F3ExMpQrvO6+JkrnABDfNqrszlvzIz51HarxQyGKXCsMvKXTFOz/ENHYz5LatEfbtlxFdFJxu7DJEA351xscLwqc1sC8+0BA75HO3Az0uFgqcnRnD096SM7MRntmgow/+oCKkmOztA0mXYHHjRRXgMvMmt9TdUe5C5snCqWp6w1rQTzBV9BcvLoqv9PrRk0MvTxiq2kmV7OmOYu53Q4abhjuRRUyc+Ie0uS2fibhFuKqOPCnpfq5KMS3buxACpXDCXQGu6MddCqqZYKZfvtRaTBdSLJYOLZorX1DD0XuHIxZY6q1yd0KS43JSmCYervQc7hD5qVJrHUFCjvDG/d1cnsSTJPQ6JEDP+fDjA8z9Q="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
